name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build frontend
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'https://your-backend-domain.com/api' }}
        
    - name: Test build
      run: |
        if [ -d "dist" ]; then
          echo "✅ Build successful - dist folder created"
          ls -la dist/
        else
          echo "❌ Build failed - no dist folder"
          exit 1
        fi

  backend-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || contains(github.event.head_commit.message, 'backend')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install backend dependencies
      run: |
        if [ -d "backend" ]; then
          cd backend
          npm ci
        else
          echo "No backend directory found"
        fi
        
    - name: Test backend
      run: |
        if [ -d "backend" ]; then
          cd backend
          npm test || echo "No tests configured"
        fi
